BMD-4600 pipeline
BerlingskeMedia/nyhedsbreveprofiladmin pull request #40
Opened 2020-12-02 06:05 UTC by bmxmaza

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-4600

2020-12-02 06:13 UTC, bmxpiku submitted a review, later dismissed

2020-12-02 06:24 UTC, bmxkrbu submitted a review, later dismissed

2021-01-04 11:45 UTC, dgolabek-sii requested changes

2021-01-04 11:45 UTC, dgolabek-sii commented on client/app/components/mdbapi.service.js
> +            console.log('INT1');
Please remove this and other debug console logs from this file.

2021-01-04 13:22 UTC, dgolabek-sii submitted a review, later dismissed

2021-02-02 07:54 UTC, merged