BMD-6296 add user cleanup list
BerlingskeMedia/nyhedsbreveprofiladmin pull request #46
Opened 2021-02-25 12:19 UTC by bmxpiku

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-6296

2021-02-25 13:07 UTC, dgolabek-sii requested changes

2021-02-25 13:07 UTC, dgolabek-sii commented on client/app/components/mdbapi.service.js
> +              .then(_httpSuccessCallback);
you are not using those params, are you?

2021-02-25 13:07 UTC, dgolabek-sii commented on client/app/cleanup/user.controller.js
> +    var vm = this;
var?

2021-02-25 13:07 UTC, dgolabek-sii commented on client/app/cleanup/user.controller.js
> +      console.log('eloszka ziomeczki');
console logs? :)

2021-02-25 13:07 UTC, dgolabek-sii commented on client/app/cleanup/user.controller.js
> +      console.log('I hope you know what are you doing');
user doesn't see that "alert" :P

2021-02-25 13:07 UTC, bmxpiku commented on client/app/cleanup/user.controller.js
> +      console.log('I hope you know what are you doing');
i know :D

2021-02-26 08:13 UTC, dgolabek-sii requested changes

2021-02-26 08:13 UTC, dgolabek-sii commented on client/app/cleanup/user.list.html
> +<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
exampleModal ;-)

2021-02-26 13:29 UTC, dgolabek-sii approved these changes

2021-03-03 09:28 UTC, bmxmaza approved these changes

2021-03-03 09:52 UTC, merged